from IAlgorithm import IAlgorithm
from IFeatureSelection import IFeatureSelection
from SequentialFeatureSelector import SequentialFeatureSelector
from SupportVectorRegression import SupportVectorRegression